AllCops:
  TargetRubyVersion: 2.5

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false
