version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  "ruby-2.3": # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/ruby:2.3
        environment: # environment variables for primary container
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory

      # Restore bundle cache
      - restore_cache:
          keys:
            - pco-url-bundle-v2-ruby23-{{ checksum "pco-url.gemspec" }}
            - pco-url-bundle-v2-ruby23-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: pco-url-bundle-v2-ruby23-{{ checksum "pco-url.gemspec" }}
          paths:
            - vendor/bundle

      - run:
          name: Run rspec
          command: |
            bundle exec rspec --format progress

  "ruby-2.4": # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/ruby:2.4
        environment: # environment variables for primary container
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory

      # Restore bundle cache
      - restore_cache:
          keys:
            - pco-url-bundle-v2-ruby24-{{ checksum "pco-url.gemspec" }}
            - pco-url-bundle-v2-ruby24-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: pco-url-bundle-v2-ruby24-{{ checksum "pco-url.gemspec" }}
          paths:
            - vendor/bundle

      - run:
          name: Run rspec
          command: |
            bundle exec rspec --format progress

workflows:
  version: 2
  build:
    jobs:
      - "ruby-2.3"
      - "ruby-2.4"
