version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout

      - restore_cache:
          keys:
            - pco-url-bundle-v2-{{ checksum ".ruby-version" }}-{{ checksum "pco-url.gemspec" }}-{{ checksum "Appraisals" }}
            - pco-url-bundle-v2-{{ checksum ".ruby-version" }}-{{ checksum "pco-url.gemspec" }}
            - pco-url-bundle-v2-{{ checksum ".ruby-version" }}-
            - pco-url-bundle-v2-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - run:
          name: Install appraisal dependencies
          command: bundle exec appraisal bundle check || bundle exec appraisal bundle install

      - save_cache:
          key: pco-url-bundle-v2-{{ checksum ".ruby-version" }}-{{ checksum "pco-url.gemspec" }}-{{ checksum "Appraisals" }}
          paths:
            - vendor/bundle

      - run:
          name: Run rspec
          command: bundle exec appraisal rspec --format progress
